[server]
maxUploadSize = 50
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#14365d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f9"
textColor = "#14202e"
